# Generated by Django 2.2.5 on 2020-01-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_auto_20200108_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberstories',
            name='Description',
            field=models.CharField(max_length=100),
        ),
    ]
